lrate: 0.1
scale: 120
max-cycles: 4096
min-basin: 0.1
map:
  dimension:
    - 1024
    - 1024
water:
  max-age: 1024
  evap-rate: 0.001
  deposition-rate: 0.05
  min-vol: 0.001
  entrainment: 10.0
  gravity: 2.0
  momentum-transfer: 1.0
