lrate: 0.1
scale: 80
max-cycles: 16384
min-basin: 0.01
water-scale: 5.0
map:
  max-depth: 16
  dimension:
    - 512
    - 512
water:
  max-age: 960
  evap-rate: 0.001
  deposition-rate: 0.05
  min-vol: 0.001
  entrainment: 10.0
  gravity: 2.0
  momentum-transfer: 1.0
matrix:
  - max-diff: 0.9
    color:
      - 0
      - 0
      - 0
  - max-diff: 0.0
    color:
      - 0
      - 0
      - 0